<?php

namespace App\Models;

use Dcat\Admin\Traits\HasDateTimeFormatter;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Deposit extends Model
{
	use HasDateTimeFormatter;
    use SoftDeletes;

    protected $table = 'deposit';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updating(function ($model){
            if($model->getOriginal('status') !== 0){
                admin_error('訂單類型錯誤!');
            }

            if($model->status > 2 || $model->status < 1){
                admin_error('訂單類型錯誤!');
            }

            if($model->status == 1){
                self::setSuccess(
                    $model,
                    $model->getOriginal('user_id'),
                    $model->getOriginal('money')
                );
            }

            if($model->status == 2){
                self::setFail($model->getOriginal('user_id'));
            }
        });
    }

    private static function setSuccess($model, $user_id, $money){
        DB::beginTransaction();
        try{
            $user = Member::query()->sharedLock()->find($user_id);
            $model->before = $user->balance;
            $model->after = $user->balance + $model->money;
            $user->balance += $money;
            $model->real = $user->balance;
            $user->save();
            DB::commit();
        }catch (\Exception $exception){
            admin_error($exception);
            DB::rollBack();
        }
    }

    private static function setFail($model){

    }
}
